const generateRandomNum = (max) => Math.floor(Math.random() * max);

const shuffleArray = (arr) => {
  const maxIndex = arr.length - 1;
  for (let i = 0; i < arr.length; i += 1) {
    let randomIndex = generateRandomNum(maxIndex);
    let currItem = arr[i];
    arr[i] = arr[randomIndex];
    arr[randomIndex] = currItem;
  }
  return arr;
};

const generatePairIdArray = (num) => {
  const shuffledIcons = shuffleArray(iconsList);
  const idArray = [];
  for (let i = 0; i < num; i += 1) {
    let id = generateRandomNum(num);
    if (
      checkIncludes(idArray, `${id}-1`) ||
      checkIncludes(idArray, `${id}-2`)
    ) {
      i -= 1;
    } else {
      idArray.push(createTilesObj(`${id}-1`, i, shuffledIcons));
      idArray.push(createTilesObj(`${id}-2`, i, shuffledIcons));
    }
  }
  const shuffledArray = shuffleArray(idArray);
  return shuffledArray;
};

const checkIncludes = (arr, idToCheck) => {
  for (let i = 0; i < arr.length; i += 1) {
    let item = arr[i]["uniqueId"];
    if (item === idToCheck) {
      return true;
    }
  }
  return false;
};

const createTilesObj = (id, index, arr) => {
  return {
    uniqueId: id,
    image: arr[index],
  };
};

/** Function to calculate total number of tiles to display based on the current round */
const calNumOfTiles = (rounds) => {
  const baseTilesNum = 8;
  let tilesIncrement = 4;

  let totalTiles = baseTilesNum;

  for (let i = 0; i < rounds; i += 1) {
    totalTiles += tilesIncrement;
  }
  return totalTiles;
};

/** Function to generate an array of unique pairs of id */
export const generateID = (rounds) => {
  const totalTilesRequired = calNumOfTiles(rounds);
  const numOfIdRequired = totalTilesRequired / 2;
  const idArray = generatePairIdArray(numOfIdRequired);
  return idArray;
};

// export const getImage = async () => {
//   const url =
//     "https://pixabay.com/api/?key=33005366-cde6083ff2884674f769fc4c5&q=yellow+flowers&image_type=photo&pretty=true&per_page=200";
//   const response = await fetch(url);
//   const data = await response.json();

//   console.log(data);
// };

const iconsList = [
  "42-group.svg",
  "500px.svg",
  "accessible-icon.svg",
  "accusoft.svg",
  "adn.svg",
  "adversal.svg",
  "affiliatetheme.svg",
  "airbnb.svg",
  "algolia.svg",
  "alipay.svg",
  "amazon-pay.svg",
  "amazon.svg",
  "amilia.svg",
  "android.svg",
  "angellist.svg",
  "angrycreative.svg",
  "angular.svg",
  "app-store-ios.svg",
  "app-store.svg",
  "apper.svg",
  "apple-pay.svg",
  "apple.svg",
  "artstation.svg",
  "asymmetrik.svg",
  "atlassian.svg",
  "audible.svg",
  "autoprefixer.svg",
  "avianex.svg",
  "aviato.svg",
  "aws.svg",
  "bandcamp.svg",
  "battle-net.svg",
  "behance.svg",
  "bilibili.svg",
  "bimobject.svg",
  "bitbucket.svg",
  "bitcoin.svg",
  "bity.svg",
  "black-tie.svg",
  "blackberry.svg",
  "blogger-b.svg",
  "blogger.svg",
  "bluetooth-b.svg",
  "bluetooth.svg",
  "bootstrap.svg",
  "bots.svg",
  "btc.svg",
  "buffer.svg",
  "buromobelexperte.svg",
  "buy-n-large.svg",
  "buysellads.svg",
  "canadian-maple-leaf.svg",
  "cc-amazon-pay.svg",
  "cc-amex.svg",
  "cc-apple-pay.svg",
  "cc-diners-club.svg",
  "cc-discover.svg",
  "cc-jcb.svg",
  "cc-mastercard.svg",
  "cc-paypal.svg",
  "cc-stripe.svg",
  "cc-visa.svg",
  "centercode.svg",
  "centos.svg",
  "chrome.svg",
  "chromecast.svg",
  "cloudflare.svg",
  "cloudscale.svg",
  "cloudsmith.svg",
  "cloudversify.svg",
  "cmplid.svg",
  "codepen.svg",
  "codiepie.svg",
  "confluence.svg",
  "connectdevelop.svg",
  "contao.svg",
  "cotton-bureau.svg",
  "cpanel.svg",
  "creative-commons-by.svg",
  "creative-commons-nc-eu.svg",
  "creative-commons-nc-jp.svg",
  "creative-commons-nc.svg",
  "creative-commons-nd.svg",
  "creative-commons-pd-alt.svg",
  "creative-commons-pd.svg",
  "creative-commons-remix.svg",
  "creative-commons-sa.svg",
  "creative-commons-sampling-plus.svg",
  "creative-commons-sampling.svg",
  "creative-commons-share.svg",
  "creative-commons-zero.svg",
  "creative-commons.svg",
  "critical-role.svg",
  "css3-alt.svg",
  "css3.svg",
  "cuttlefish.svg",
  "d-and-d-beyond.svg",
  "d-and-d.svg",
  "dailymotion.svg",
  "dashcube.svg",
  "deezer.svg",
  "delicious.svg",
  "deploydog.svg",
  "deskpro.svg",
  "dev.svg",
  "deviantart.svg",
  "dhl.svg",
  "diaspora.svg",
  "digg.svg",
  "digital-ocean.svg",
  "discord.svg",
  "discourse.svg",
  "dochub.svg",
  "docker.svg",
  "draft2digital.svg",
  "dribbble.svg",
  "dropbox.svg",
  "drupal.svg",
  "dyalog.svg",
  "earlybirds.svg",
  "ebay.svg",
  "edge-legacy.svg",
  "edge.svg",
  "elementor.svg",
  "ello.svg",
  "ember.svg",
  "empire.svg",
  "envira.svg",
  "erlang.svg",
  "ethereum.svg",
  "etsy.svg",
  "evernote.svg",
  "expeditedssl.svg",
  "facebook-f.svg",
  "facebook-messenger.svg",
  "facebook.svg",
  "fantasy-flight-games.svg",
  "fedex.svg",
  "fedora.svg",
  "figma.svg",
  "firefox-browser.svg",
  "firefox.svg",
  "first-order-alt.svg",
  "first-order.svg",
  "firstdraft.svg",
  "flickr.svg",
  "flipboard.svg",
  "fly.svg",
  "font-awesome.svg",
  "fonticons-fi.svg",
  "fonticons.svg",
  "fort-awesome-alt.svg",
  "fort-awesome.svg",
  "forumbee.svg",
  "foursquare.svg",
  "free-code-camp.svg",
  "freebsd.svg",
  "fulcrum.svg",
  "galactic-republic.svg",
  "galactic-senate.svg",
  "get-pocket.svg",
  "gg-circle.svg",
  "gg.svg",
  "git-alt.svg",
  "git.svg",
  "github-alt.svg",
  "github.svg",
  "gitkraken.svg",
  "gitlab.svg",
  "gitter.svg",
  "glide-g.svg",
  "glide.svg",
  "gofore.svg",
  "golang.svg",
  "goodreads-g.svg",
  "goodreads.svg",
  "google-drive.svg",
  "google-pay.svg",
  "google-play.svg",
  "google-plus-g.svg",
  "google-plus.svg",
  "google-wallet.svg",
  "google.svg",
  "gratipay.svg",
  "grav.svg",
  "gripfire.svg",
  "grunt.svg",
  "guilded.svg",
  "gulp.svg",
  "hacker-news.svg",
  "hackerrank.svg",
  "hashnode.svg",
  "hips.svg",
  "hire-a-helper.svg",
  "hive.svg",
  "hooli.svg",
  "hornbill.svg",
  "hotjar.svg",
  "houzz.svg",
  "html5.svg",
  "hubspot.svg",
  "ideal.svg",
  "imdb.svg",
  "instagram.svg",
  "instalod.svg",
  "intercom.svg",
  "internet-explorer.svg",
  "invision.svg",
  "ioxhost.svg",
  "itch-io.svg",
  "itunes-note.svg",
  "itunes.svg",
  "java.svg",
  "jedi-order.svg",
  "jenkins.svg",
  "jira.svg",
  "joget.svg",
  "joomla.svg",
  "js.svg",
  "jsfiddle.svg",
  "kaggle.svg",
  "keybase.svg",
  "keycdn.svg",
  "kickstarter-k.svg",
  "kickstarter.svg",
  "korvue.svg",
  "laravel.svg",
  "lastfm.svg",
  "leanpub.svg",
  "less.svg",
  "line.svg",
  "linkedin-in.svg",
  "linkedin.svg",
  "linode.svg",
  "linux.svg",
  "lyft.svg",
  "magento.svg",
  "mailchimp.svg",
  "mandalorian.svg",
  "markdown.svg",
  "mastodon.svg",
  "maxcdn.svg",
  "mdb.svg",
  "medapps.svg",
  "medium.svg",
  "medrt.svg",
  "meetup.svg",
  "megaport.svg",
  "mendeley.svg",
  "meta.svg",
  "microblog.svg",
  "microsoft.svg",
  "mix.svg",
  "mixcloud.svg",
  "mixer.svg",
  "mizuni.svg",
  "modx.svg",
  "monero.svg",
  "napster.svg",
  "neos.svg",
  "nfc-directional.svg",
  "nfc-symbol.svg",
  "nimblr.svg",
  "node-js.svg",
  "node.svg",
  "npm.svg",
  "ns8.svg",
  "nutritionix.svg",
  "octopus-deploy.svg",
  "odnoklassniki.svg",
  "old-republic.svg",
  "opencart.svg",
  "openid.svg",
  "opera.svg",
  "optin-monster.svg",
  "orcid.svg",
  "osi.svg",
  "padlet.svg",
  "page4.svg",
  "pagelines.svg",
  "palfed.svg",
  "patreon.svg",
  "paypal.svg",
  "perbyte.svg",
  "periscope.svg",
  "phabricator.svg",
  "phoenix-framework.svg",
  "phoenix-squadron.svg",
  "php.svg",
  "pied-piper-alt.svg",
  "pied-piper-hat.svg",
  "pied-piper-pp.svg",
  "pied-piper.svg",
  "pinterest-p.svg",
  "pinterest.svg",
  "pix.svg",
  "playstation.svg",
  "product-hunt.svg",
  "pushed.svg",
  "python.svg",
  "qq.svg",
  "quinscape.svg",
  "quora.svg",
  "r-project.svg",
  "raspberry-pi.svg",
  "ravelry.svg",
  "react.svg",
  "reacteurope.svg",
  "readme.svg",
  "rebel.svg",
  "red-river.svg",
  "reddit-alien.svg",
  "reddit.svg",
  "redhat.svg",
  "renren.svg",
  "replyd.svg",
  "researchgate.svg",
  "resolving.svg",
  "rev.svg",
  "rocketchat.svg",
  "rockrms.svg",
  "rust.svg",
  "safari.svg",
  "salesforce.svg",
  "sass.svg",
  "schlix.svg",
  "screenpal.svg",
  "scribd.svg",
  "searchengin.svg",
  "sellcast.svg",
  "sellsy.svg",
  "servicestack.svg",
  "shirtsinbulk.svg",
  "shopify.svg",
  "shopware.svg",
  "simplybuilt.svg",
  "sistrix.svg",
  "sith.svg",
  "sitrox.svg",
  "sketch.svg",
  "skyatlas.svg",
  "skype.svg",
  "slack.svg",
  "slideshare.svg",
  "snapchat.svg",
  "soundcloud.svg",
  "sourcetree.svg",
  "space-awesome.svg",
  "speakap.svg",
  "speaker-deck.svg",
  "spotify.svg",
  "square-behance.svg",
  "square-dribbble.svg",
  "square-facebook.svg",
  "square-font-awesome-stroke.svg",
  "square-font-awesome.svg",
  "square-git.svg",
  "square-github.svg",
  "square-gitlab.svg",
  "square-google-plus.svg",
  "square-hacker-news.svg",
  "square-instagram.svg",
  "square-js.svg",
  "square-lastfm.svg",
  "square-odnoklassniki.svg",
  "square-pied-piper.svg",
  "square-pinterest.svg",
  "square-reddit.svg",
  "square-snapchat.svg",
  "square-steam.svg",
  "square-tumblr.svg",
  "square-twitter.svg",
  "square-viadeo.svg",
  "square-vimeo.svg",
  "square-whatsapp.svg",
  "square-xing.svg",
  "square-youtube.svg",
  "squarespace.svg",
  "stack-exchange.svg",
  "stack-overflow.svg",
  "stackpath.svg",
  "staylinked.svg",
  "steam-symbol.svg",
  "steam.svg",
  "sticker-mule.svg",
  "strava.svg",
  "stripe-s.svg",
  "stripe.svg",
  "studiovinari.svg",
  "stumbleupon-circle.svg",
  "stumbleupon.svg",
  "superpowers.svg",
  "supple.svg",
  "suse.svg",
  "swift.svg",
  "symfony.svg",
  "teamspeak.svg",
  "telegram.svg",
  "tencent-weibo.svg",
  "the-red-yeti.svg",
  "themeco.svg",
  "themeisle.svg",
  "think-peaks.svg",
  "tiktok.svg",
  "trade-federation.svg",
  "trello.svg",
  "tumblr.svg",
  "twitch.svg",
  "twitter.svg",
  "typo3.svg",
  "uber.svg",
  "ubuntu.svg",
  "uikit.svg",
  "umbraco.svg",
  "uncharted.svg",
  "uniregistry.svg",
  "unity.svg",
  "unsplash.svg",
  "untappd.svg",
  "ups.svg",
  "usb.svg",
  "usps.svg",
  "ussunnah.svg",
  "vaadin.svg",
  "viacoin.svg",
  "viadeo.svg",
  "viber.svg",
  "vimeo-v.svg",
  "vimeo.svg",
  "vine.svg",
  "vk.svg",
  "vnv.svg",
  "vuejs.svg",
  "watchman-monitoring.svg",
  "waze.svg",
  "weebly.svg",
  "weibo.svg",
  "weixin.svg",
  "whatsapp.svg",
  "whmcs.svg",
  "wikipedia-w.svg",
  "windows.svg",
  "wirsindhandwerk.svg",
  "wix.svg",
  "wizards-of-the-coast.svg",
  "wodu.svg",
  "wolf-pack-battalion.svg",
  "wordpress-simple.svg",
  "wordpress.svg",
  "wpbeginner.svg",
  "wpexplorer.svg",
  "wpforms.svg",
  "wpressr.svg",
  "xbox.svg",
  "xing.svg",
  "y-combinator.svg",
  "yahoo.svg",
  "yammer.svg",
  "yandex-international.svg",
  "yandex.svg",
  "yarn.svg",
  "yelp.svg",
  "yoast.svg",
  "youtube.svg",
  "zhihu.svg",
];

const emojiImages = [
  "1f3a0.png",
  "1f3a1.png",
  "1f3a2.png",
  "1f3a3.png",
  "1f3a4.png",
  "1f3a5.png",
  "1f3a6.png",
  "1f3a7.png",
  "1f3a8.png",
  "1f3a9.png",
  "1f3aa.png",
  "1f3ab.png",
  "1f3ac.png",
  "1f3ad.png",
  "1f3ae.png",
  "1f3af.png",
  "1f3b0.png",
  "1f3b1.png",
  "1f3b2.png",
  "1f3b3.png",
  "1f3b4.png",
  "1f3b5.png",
  "1f3b6.png",
  "1f3b7.png",
  "1f3b8.png",
  "1f3b9.png",
  "1f3ba.png",
  "1f3bb.png",
  "1f3bc.png",
  "1f3bd.png",
  "1f3be.png",
  "1f3bf.png",
  "1f3c0.png",
  "1f3c1.png",
  "1f3cd-fe0f.png",
  "1f3ce-fe0f.png",
  "1f3cf.png",
  "1f3d0.png",
  "1f3d1.png",
  "1f3d2.png",
  "1f3d3.png",
  "1f3d4-fe0f.png",
  "1f3d5-fe0f.png",
  "1f3d6-fe0f.png",
  "1f3d7-fe0f.png",
  "1f3d8-fe0f.png",
  "1f3d9-fe0f.png",
  "1f3da-fe0f.png",
  "1f3db-fe0f.png",
  "1f3dc-fe0f.png",
  "1f3dd-fe0f.png",
  "1f3de-fe0f.png",
  "1f3df-fe0f.png",
  "1f3ee.png",
  "1f3ef.png",
  "1f3f0.png",
  "1f3f3-fe0f.png",
  "1f3f4-200d-2620-fe0f.png",
  "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png",
  "1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png",
  "1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png",
  "1f3f4.png",
  "1f3f5-fe0f.png",
  "1f3f7-fe0f.png",
  "1f3f8.png",
  "1f3f9.png",
  "1f3fa.png",
  "1f004.png",
  "1f4a0.png",
  "1f4a1.png",
  "1f4a2.png",
  "1f4a3.png",
  "1f4a4.png",
  "1f4a5.png",
  "1f4a6.png",
  "1f4a7.png",
  "1f4a8.png",
  "1f4a9.png",
  "1f4ab.png",
  "1f4ac.png",
  "1f4ad.png",
  "1f4ae.png",
  "1f4af.png",
  "1f4b0.png",
  "1f4b1.png",
  "1f4b2.png",
  "1f4b3.png",
  "1f4b5.png",
  "1f4ba.png",
  "1f4bb.png",
  "1f4bc.png",
  "1f4bd.png",
  "1f4c0.png",
  "1f4c1.png",
  "1f4c6.png",
  "1f4c7.png",
  "1f4c8.png",
  "1f4c9.png",
  "1f4ca.png",
  "1f4cb.png",
  "1f4cc.png",
  "1f4cd.png",
  "1f4ce.png",
  "1f4cf.png",
  "1f4d0.png",
  "1f4d1.png",
  "1f4d2.png",
  "1f4d3.png",
  "1f4d4.png",
  "1f4d6.png",
  "1f4db.png",
  "1f4dc.png",
  "1f4dd.png",
  "1f4de.png",
  "1f4df.png",
  "1f4e0.png",
  "1f4e1.png",
  "1f4e2.png",
  "1f4e3.png",
  "1f4e4.png",
  "1f4e5.png",
  "1f4e6.png",
];
